name: gatta
favicon: null
layout_spectrum: 0.76004
typography_spectrum: 0.3379
title: 'Rachel alias Dirtbiking Gatta '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7fff6'
    - '#12130e'
    - '#b52908'
    - '#738088'
    - '#ff9809'
  brandStrength: 0.7035042147617787
  lightness: 0.062421242939308286
  saturation: 0.5857214941643178
  rhythmicContrast: 0.6709816192742437
purpose: []
